config/routes.rb
Ticketea::Application.routes.draw do
  # first created -> highest priority.

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
      :to => "users#confirmation",
      :as => 'confirm_user'

  resources :projects do
    resources :tickets
  end

  root :to => "projects#index"
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end

  put '/admin/users/:user_id/permissions',
                    :to => 'admin/permissions#update',
                    :as => :update_user_permissions

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  has_many :tickets, :dependent => :delete_all
  has_many :permissions, :as => :thing

  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => { :action => "view",
                                                :user_id => user.id })
  }

  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only => [:show, :index]
  before_filter :find_project, :only => [:show, :edit, :update, :destroy]
  def show
    @tickets = @project.tickets
  end

  def index
    @projects = Project.for(current_user).all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => 'Project has been created.'
    else
      flash[:alert] = 'Project has not been created.'
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  private
    def find_project
      @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  %p=f.error_messages
  %p
    =f.label :name
    =f.text_field :name
  =f.submit

app/views/projects/_project.html.haml
%li= link_to project.name, project

app/views/projects/edit.html.haml
%h2 Edit Project
= render 'form'

app/views/projects/index.html.haml
%h2 Projects
%ul= render @projects

- admins_only do
  = link_to "New Project", new_project_path

app/views/projects/new.html.haml
= render 'form'

app/views/projects/show.html.haml
- title(@project.name, "Projects")
%h2= @project.name
%ul#tickets= render @tickets unless @tickets.empty?
- admins_only do
  = link_to "Edit Project", edit_project_path(@project)
  = link_to "Delete Project", @project, :method => :delete, :confirm => 'Are you sure you want to delete this project?'
= authorized?("create tickets".to_sym, @project) do
  = link_to "New Ticket", new_project_ticket_path(@project)