config/routes.rb
Ticketea::Application.routes.draw do
  # first created -> highest priority.

  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
      :to => "users#confirmation",
      :as => 'confirm_user'

  resources :projects do
    resources :tickets
  end

  root :to => "projects#index"
  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
  end

  put '/admin/users/:user_id/permissions',
                    :to => 'admin/permissions#update',
                    :as => :update_user_permissions

end

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

app/views/layouts/_footer.html.haml
%small.copyright
  Copyright &copy; #{Date.today.year}

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title
  -if content_for?(:title)
    = yield(:title)
  -else
    Ticketee

%meta{ :name => "description", :content => "" }/
%meta{ :name => "author", :content => "" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

-# Pass in a stylesheet_partial to render inside your head
- if local_assigns[:stylesheet_partial]
  = render :partial => local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr and Respond.
-# Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
= javascript_include_tag 'modernizr+respond'

= csrf_meta_tag

app/views/layouts/_header.html.haml
%h1= link_to "Ticketee", root_path

-if user_signed_in?
  %p
    Signed in as
    = current_user.email
    = link_to "Sign out", destroy_user_session_path, :method => :delete
    - admins_only do
      %nav= link_to "Admin", admin_root_path
-else
  %nav
    = link_to "Sign up", new_user_registration_path
    = link_to "Sign in", new_user_session_path

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
- if !google_api_key.blank?
  = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load(#{ remote_jquery("1.6") });
- else
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.6") }"

-# fall back to local jQuery if necessary
:javascript
  window.jQuery || document.write("#{escape_javascript(javascript_include_tag('jquery'))}")
  
= javascript_include_tag 'application'
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"],["_trackPageLoadTime"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'application', :media => 'all'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    -# To render a different stylesheet partial inside the head (i.e. for admin layout)
    -# just copy _stylesheets.html.haml, and point to that partial instead.
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"
  
  %body{ :class => "#{controller.controller_name}" }
    #container
      %header#header
        = render "layouts/header"
        
      #main{ :role => 'main' }
        = render "layouts/flashes"
        = yield
        
      %footer#footer
        = render "layouts/footer"
        
    -# Javascript at the bottom for fast page loading
    = render "layouts/javascripts"